### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by davidhaley** [sevagh/free-music-demixer#5]
3080 GPU

```
  0%|                                                                                                                                                                                         | 0/1 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/.virtualenvs/demixer/bin/umx", line 8, in <module>
    sys.exit(separate())
             ^^^^^^^^^^
  File "/free-music-demixer/vendor/open-unmix-pytorch/openunmix/cli.py", line 167, in separate
    estimates = predict.separate(
                ^^^^^^^^^^^^^^^^^
  File "/free-music-demixer/vendor/open-unmix-pytorch/openunmix/predict.py", line 78, in separate
    estimates = separator(audio)
                ^^^^^^^^^^^^^^^^
  File "/home/user/.virtualenvs/demixer/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/free-music-demixer/vendor/open-unmix-pytorch/openunmix/model.py", line 314, in forward
    targets_stft = targets_stft.permute(0, 5, 3, 2, 1, 4).contiguous()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.56 GiB (GPU 0; 9.77 GiB total capacity; 5.71 GiB already allocated; 1.37 GiB free; 6.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by sevagh** [comment]
This is a problem with the vendored [open-unmix-pytorch](https://github.com/sigsep/open-unmix-pytorch) code. How big is your track? You should probably use the CPU for inference on a large track.

**Comment by davidhaley** [comment]
It's about 8 minutes. Using the CPU worked - thanks!
